title: Résumé

footer:
  enable: true # decide where you want to show  your footer
  copyright:  # customize your copyright in footer, e.g. © 2019-2020 Zhiwei Li
    startYear: 2019
    currentYear: 2020
    author: daxiongpro
    link: https://github.com/mtics/hexo-mtics-resume
    beian: 


################################
#     Write your resume Here   #
################################
resume:
  name: Cai Zhengyi
  jobtitle: Algorithm Engineer
  portrait: img/myphoto.png # author's portrait
  contact:
    - icon: fa-envelope
      text: 910660298@qq.com
    - icon: fa-phone-square
      text: 86+17815961210
    - icon: fa-globe
      text: homepage
      link: daxiongpro.github.io
    - icon: fa-github
      text: github
      link: https://github.com/daxiongpro
  education:
    - university: Ningbo University (NBU)
      duration: Sep 2019 - Jul 2022
      location: Ningbo, Zhejiang, China
      major: Python, Neual Network, Point cloud deep learning, Computer vision
    - university: Qingdao University (QDU)
      duration: Aug 2015 - Jul 2019
      location: Qingdao, Shandong, China
      major: C, Java, Javascript, MySQL, Algorithms
  experience:
    - title: Geely Research
      duration: Oct 2021 - Now
      company: Your 2st, Inc.
      description: 1.Make some algorithm study about 3D object detection(3DSSD for example). \n2.Deploy the algorithm on ROS2. 
    # - title: Job Title 2
    #   duration: Apr 2013 - Mar 2016
    #   company: Your 2nd, Inc.
    #   description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    # - title: Job Title 3
    #   duration: Dec 2011 - Mar 2012
    #   company: Your 3rd Co, Ltd.
    #   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  projects:
    - name: Smart assemble assistant
      description:  1.
      contribution: Contributor.
    - name: Project Name 2
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Creator and maintainer.
  skills:
    - title: Programming
      items: Python, Pytorch, Linux
    - title: Other
      items: CET-6, Driver Licence -C1
    # - title: Skill Group 3
    #   items: Sed do, Eiusmod, Tempor, Incididunt
